# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/vivo/2026/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/vivo/2026

PRODUCT_COPY_FILES += \
    vendor/vivo/2026/proprietary/bin/kpoc_charger:$(TARGET_COPY_OUT_SYSTEM)/bin/kpoc_charger \
    vendor/vivo/2026/proprietary/etc/init/kpoc_charger.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/kpoc_charger.rc \
    vendor/vivo/2026/proprietary/lib/libshowlogo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libshowlogo.so \
    vendor/vivo/2026/proprietary/lib64/libaptXHD_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptXHD_encoder.so \
    vendor/vivo/2026/proprietary/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptX_encoder.so

PRODUCT_PACKAGES += \
    EngineerMode \
    ImsService